### PR TITLE
feat(opentelemetry): add resource to the trace example

### PR DESCRIPTION
**Pull request by dashpole**
This adds attributes to the trace produced by the example, depending on the platform.  When I tried it on a GCE instance, I got:

* cloud.account.id
* cloud.availability_zone
* cloud.platform
* cloud.provider
* cloud.region
* g.co/agent
* host.id
* host.name
* host.type
* telemetry.sdk.language
* telemetry.sdk.name
* telemetry.sdk.version

### CODE REVIEW

**Review by codyoss — APPROVED** [review]
LGTM, thanks

**Comment by dashpole** [comment]
fixed the commit message

**Review by punya — APPROVED** [review]

**Comment by dashpole** [comment]
@codyoss Is there anything else this needs to be merged?  Thanks!

**Comment by codyoss** [comment]
@dashpole nope, all good!

**Pull request merged**
