### PR TITLE
getting-started: listen on PORT

### PR DESCRIPTION
**Pull request by kemokemo**
Hi!

I'm a beginner of GCP and learning the GCP with the official tutorials.
First of all, thak you so much the very nice tutorials! 😃 

## Issue

I was practicing the [this tutorial](https://cloud.google.com/go/docs/tutorials/bookshelf-on-kubernetes-engine), but panic occurred at the frontend 'app' and it did not work. The error log that occurred at that time was confirmed with Stackdriver below.

```json
{
    "textPayload": "panic: Metadata fetch failed for 'instance/attributes/gae_project': metadata server returned HTTP 404\n\ngoroutine 89 [running]:\ngoogle.golang.org/appengine/internal.mustGetMetadata(0xb7d3a3, 0x1f, 0x0, 0x0, 0x0)\n\t/go/src/google.golang.org/appengine/internal/metadata.go:34 +0x18a\ngoogle.golang.org/appengine/internal.partitionlessAppID(0x0, 0xc000262600)\n\t/go/src/google.golang.org/appengine/internal/identity_vm.go:112 +0xa2\ngoogle.golang.org/appengine/internal.DefaultTicket.func1()\n\t/go/src/google.golang.org/appengine/internal/api.go:293 +0x86\nsync.(*Once).Do(0x112f6c8, 0xb98848)\n\t/usr/local/go/src/sync/once.go:44 +0xb3\ngoogle.golang.org/appengine/internal.DefaultTicket(0xc0007d1dd0, 0xa117c0)\n\t/go/src/google.golang.org/appengine/internal/api.go:288 +0x39\ngoogle.golang.org/appengine/internal.Call(0xc1f0e0, 0xc0007d1dd0, 0xb6e0c3, 0xa, 0xb695e4, 0x5, 0xc1c420, 0xc000262600, 0xc1b620, 0xc00040e0e0, ...)\n\t/go/src/google.golang.org/appengine/internal/api.go:495 +0x852\ngoogle.golang.org/appengine/internal.(*context).flushLog(0xc000444900, 0xb99401, 0xc0005cc200)\n\t/go/src/google.golang.org/appengine/internal/api.go:637 +0x3d0\ngoogle.golang.org/appengine/internal.handleHTTP.func1(0xc0005cc2a0, 0xc000444900)\n\t/go/src/google.golang.org/appengine/internal/api.go:137 +0x56\ncreated by google.golang.org/appengine/internal.handleHTTP\n\t/go/src/google.golang.org/appengine/internal/api.go:133 +0x350\n",
    "insertId": "1kvvdxfg3s9go81",
    "resource": {
      "type": "container",
      "labels": {
        "cluster_name": "bookshelf",
        "container_name": "bookshelf-app",
        "namespace_id": "default",
        "instance_id": "8544645641522474976",
        "pod_id": "bookshelf-frontend-5d9f864b5c-6pjxj",
        "zone": "asia-northeast1-a",
        "project_id": "mybookshelf-226812"
      }
    },
    "timestamp": "2018-12-30T07:52:57Z",
    "severity": "ERROR",
    "labels": {
      "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-n497k",
      "container.googleapis.com/pod_name": "bookshelf-frontend-5d9f864b5c-6pjxj",
      "container.googleapis.com/stream": "stderr",
      "container.googleapis.com/namespace_name": "default"
    },
    "logName": "projects/mybookshelf-226812/logs/bookshelf-app",
    "receiveTimestamp": "2018-12-30T07:53:05.999226813Z"
  },
```

When building the same app locally and executing it did not work with the following error.
```
panic: Metadata fetch failed for 'instance/attributes/gae_project': Get http://metadata/computeMetadata/v1/instance/attributes/gae_project: dial tcp: lookup metadata: no such host
```

## Changes to solve the issue

Remove the `google.golang.org/appengine` and apply the new runtime `go111` for the App Engine.
Thank you for your review.

### CODE REVIEW

**Comment by broady** [comment]
I made one change. @tbpg for final approval + merge.

**Comment by broady** [comment]
Thanks for the contribution!

**Comment by tbpg** [comment]
Thank you! LGTM - waiting for tests.

CLA looks good - was verified before @broady (a Googler) made an update.

**Comment by kemokemo** [comment]
Thank you so much for your reviewing and fixing!
I'm proud that I contributed to this wonderful GCP sample code. 😃

**Pull request merged**
