### PR TITLE
storage: add encryption samples

### PR DESCRIPTION
**Pull request by rakyll**

### CODE REVIEW

**Comment by jba** [comment]
LGTM.

**Comment by broady** [comment]
```
--- FAIL: TestObjects (13.61s)
	main_test.go:116: cleanup of bucket failed: googleapi: Error 409: The bucket you tried to delete was not empty., conflict
```

I really need to fix up and submit #116 :|

**Comment by rakyll** [comment]
Yup, please. Cleanup fails very often :(

**Pull request merged**
