### PR TITLE
spanner: use timestamp+uuid for db names

### LINKED ISSUE #1339: spanner/spanner_snippets: TestBackupSample failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: 332956446c128e9b39f462033299f88da88f84aa
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/c4593ec9-8e9c-4a16-87b0-385953d83d80), [Sponge](http://sponge2/c4593ec9-8e9c-4a16-87b0-385953d83d80)
status: failed

### PR DESCRIPTION
**Pull request by hengfengli**
This PR includes the following changes: 

- Use timestamp and uuid for db names. 
- Fix an issue in CreateInstance test due to the confusion of the env var `GOLANG_SAMPLES_PROJECT_ID`. `GOLANG_SAMPLES_PROJECT_ID` is not the actual GCP Project ID. 

Fixes #1339

### CODE REVIEW

**Comment by hengfengli** [comment]
@tbpg Only one of four tests can succeed: 

```bash
[19:40:41] Child job: cloud-devrel/go/golang-samples/presubmit/go114 finished with status: FAILED
[19:41:16] Child job: cloud-devrel/go/golang-samples/presubmit/go111 finished with status: FAILED
[19:43:51] Child job: cloud-devrel/go/golang-samples/presubmit/go112 finished with status: FAILED
[19:44:19] Child job: cloud-devrel/go/golang-samples/presubmit/go113 finished with status: SUCCEEDED
```

The error is `the maximum number of pending restores (1) for the instance is reached`: 

```bash
=== RUN   TestBackupSample
    TestBackupSample: integration_test.go:362: failed to restore a backup: rpc error: code = FailedPrecondition desc = Cannot restore database (projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1592447701-f47bb768) because the maximum number of pending restores (1) for the instance (projects/golang-samples-tests/instances/golang-samples-tests) has been reached. Please retry the operation once the pending restores complete.
```

Will go111, go112, go113, and go114, run in parallel or sequential?

**Comment by hengfengli** [comment]
I see that only go114 will run the E2E tests: 

https://github.com/GoogleCloudPlatform/golang-samples/blob/44be93cd3bc53b0b9fc8e5b075292b9d2d04b180/testing/kokoro/go114.cfg#L9-L13

https://github.com/GoogleCloudPlatform/golang-samples/blob/44be93cd3bc53b0b9fc8e5b075292b9d2d04b180/testing/kokoro/system_tests.sh#L168-L171

**Comment by tbpg** [comment]
Seems OK to me. Unfortunate it seems necessary. Adding @broady since he's expressed some opinions about UUIDs.

**Comment by hengfengli** [comment]
@tbpg @broady I just want to check if this PR is okay to merge.

**Pull request merged**
