### PR TITLE
fix(firestore): Call document iterator stop function

### LINKED ISSUE #4230: Firestore: Memory leak
## In which file did you encounter the issue?

/firestore/retrieve_data_get_all_documents.go

## Did you change the file? If so, how?

No.

## Describe the issue

I can use the sample code to get all document data from a Firestore collection, but It doesn't free the memory back after I got the data. I found out from this doc https://pkg.go.dev/cloud.google.com/go/firestore#DocumentIterator.Stop that we must call "defer iter.Stop()" when we have done a DocumentIterator

Thanks!

### PR DESCRIPTION
**Pull request by sakayaparp**
## Description

Fixes #4230 

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [ ] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [ ] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Review by Deleplace — APPROVED** [review]
LGTM

**Comment by Deleplace** [comment]
Hi @sakayaparp , I'm curious if you could measure that:
- before the change, the memory wasn't released,
- after the change, the memory was released

Thanks!

**Comment by sakayaparp** [comment]
> Hi @sakayaparp , I'm curious if you could measure that:
> 
> * before the change, the memory wasn't released,
> * after the change, the memory was released
> 
> Thanks!

Hi @Deleplace , The image below shows the memory usage encountered on my production environment.
Screenshot 2567-07-01 at 21 43 09

**Comment by Deleplace** [comment]
Awesome data, thank you @sakayaparp !

**Pull request merged**
