### PR TITLE
infinite streaming sample code

### PR DESCRIPTION
**Pull request by wangbill-google**
I have uploaded infinite streaming from file and infinite streaming from microphone sample code.

### CODE REVIEW

**Comment by wangbill-google** [comment]
kokoro:force-run

**Comment by grayside** [comment]
Current test failure is repeat occurrence of

```
rsync: send_files failed to open "/tmpfs/src/gopath/src/github.com/GoogleCloudPlatform/golang-samples/go.mod": Permission denied (13)
rsync: send_files failed to open "/tmpfs/src/gopath/src/github.com/GoogleCloudPlatform/golang-samples/go.sum": Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1677) [generator=3.1.3]
```

This seems unrelated to the PR. @tbpg do you have insights?

**Comment by tbpg** [comment]
Please run `go mod tidy`. I think that's causing the problem. I filed #1111.

**Comment by grayside** [comment]
Hi Bill,

I've started to look through the code and have an immediate question/comment:

What are you planning to do with this sample? This will inform how I review it.

An immediate feedback: please remove the go.mod and go.sum you've added, this was a miscommunication. There is already a go.mod and go.sum at the root of the repository. This needs to be updated for your code by running `go mod tidy` in the top level and committing the changes.

**Pull request closed without merging**
