### PR TITLE
appengine: remove gophers sample

### LINKED ISSUE #1178: App Engine: Remove gophers sample series
[The Gophers sample app series](https://github.com/GoogleCloudPlatform/golang-samples/appengine/gophers) is not used in current docs and has been superseded by https://cloud.google.com/go/getting-started.

This code has not been significantly maintained in over a year.

Proposal: Delete the code, possibly adding a README at /appengine/gophers with a link to the last revision in git history.

### PR DESCRIPTION
**Pull request by tbpg**
It is no longer used.

Fixes #1178.

### CODE REVIEW

**Comment by grayside** [comment]
Should we add a README to point to the dropped code or do we not anticipate wanting to resurrect?

**Comment by grayside** [comment]
Want to wait for @andrewsg on this so withholding approval for now.

**Comment by tbpg** [comment]
I don't anticipate much traffic. There are no active pages with this code (including translated pages).

**Comment by andrewsg** [comment]
No active pages, def. ok to delete from my perspective. Thanks!

**Pull request merged**
