### PR TITLE
spanner: make sample functions public and use snippet.go as a CLI wrapper

### PR DESCRIPTION
**Pull request by hengfengli**
Please DO NOT merge it at the moment. 

This PR updates `snippet.go` which is currently referenced in docs generation. The auto docs generation will be broken if this is merged. We need to coordinate the merge with the internal docs updates together.

### CODE REVIEW

**Comment by hengfengli** [comment]
> I commented on the issue. But, I'm not sure I understand why these need to be exported. We can change the package to `package main`, add a `func main`, and it will work without exporting.

@tbpg I have tried what you said, changing the package to `package main` and `func main`, but it does not work. Please see my comments on the issue.

**Comment by hengfengli** [comment]
I have created a PR that changes to `package main` and `func main` is in snippet.go: https://github.com/GoogleCloudPlatform/golang-samples/pull/1513. 

I tried the following ways to run the `snippet.go`, but they do not work. 

```bash
$ go run snippet.go createdatabase projects/[project_id]/instances/[instance_id]/databases/snippet-test-db
# command-line-arguments
./snippet.go:36:38: undefined: write
./snippet.go:37:38: use of builtin delete not in function call
./snippet.go:38:38: undefined: query
./snippet.go:39:38: undefined: read
./snippet.go:40:38: undefined: update
./snippet.go:41:38: undefined: writeWithTransaction
./snippet.go:42:38: undefined: queryNewColumn
./snippet.go:43:38: undefined: queryUsingIndex
./snippet.go:44:38: undefined: readUsingIndex
./snippet.go:45:38: undefined: readStoringIndex
./snippet.go:45:38: too many errors


$ go run *.go createdatabase projects/[project_id]/instances/[instance_id]/databases/snippet-test-db
go run: cannot run *_test.go files (integration_test.go)

$ go run . createdatabase projects/[project_id]/instances/[instance_id]/databases/snippet-test-db
# github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets
runtime.main_main·f: function main is undeclared in the main package
```

**Comment by tbpg** [comment]
`snippet.go` has a `// +build ignore` line, so that file is ignored, and there is no other `func main`. `go build` also fails with the same error. If you remove that line, you get real compile errors.

**Comment by hengfengli** [comment]
Yes, you're right. Sorry for missing this. `go run .` is working now. I will not do any changes to this PR until a final decision is made.

**Comment by tbpg** [comment]
Hey @hengfengli, what's the next step for this PR?

**Comment by hengfengli** [comment]
I don't think this PR is needed any more. I'll close this.

**Pull request closed without merging**
