### PR TITLE
feat(vertexai): Non-stream basic text sample

### PR DESCRIPTION
**Pull request by ianlewis**
## Description

Go version of the Python sample at
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/generative_ai/inference/non_stream_text_basic.py

Region tag `generativeaionvertexai_non_stream_text_basic`.

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [x] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [x] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by Deleplace** [comment]
We're leaning towards reusing the existing code samples, when possible

**Comment by ianlewis** [comment]
> This sample is LGTM, but before approving I wanted to confirm we should create this sample instead of somehow reuse https://github.com/GoogleCloudPlatform/golang-samples/blob/main/vertexai/snippets/text_input.go#L16, which seems very similar. @gericdong

I think the page contexts are a bit different, the sample on the [quickstarts page](https://cloud.google.com/vertex-ai/generative-ai/docs/start/quickstarts/quickstart-multimodal#gemini-text-only-samples-go) looks like it should support replacing the `PROJECT_ID` like the Python sample does.

However, I kind of agree that the inference API samples and these quickstart samples could probably just be reused.
https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference#non-stream-text

**Comment by ianlewis** [comment]
I do wonder about the difference in structure for the prompt passed to `generateContent` in the [Quickstart Node.js sample](https://cloud.google.com/vertex-ai/generative-ai/docs/start/quickstarts/quickstart-multimodal#gemini-text-only-samples-nodejs) and the [model inference API reference Node.js sample](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference#nodejs) but I based on the surrounding docs it doesn't seem germane.

I propose that we just use the quickstart samples for [text-only](https://cloud.google.com/vertex-ai/generative-ai/docs/start/quickstarts/quickstart-multimodal#send-text-only-request) and [audio and video](https://cloud.google.com/vertex-ai/generative-ai/docs/start/quickstarts/quickstart-multimodal#send-request-audio-video) on the model inference page for [non-streaming text](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference#non-stream-text) and [non-streaming multimodal](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference#non-stream-multi-modality) samples.

Though I think we will need to have streaming examples on the model inference page. WDUT? @grayside @gericdong

**Comment by gericdong** [comment]
@ianlewis I agree with your assessment. Thanks.

**Comment by ianlewis** [comment]
Closing. Will submit changes to the doc to reuse the existing samples.

**Pull request closed without merging**
