### PR TITLE
Check callback session state

### PR DESCRIPTION
**Pull request by huikang**
Session is invalid if it is a new session.

Signed-off-by: Hui Kang <kangh@us.ibm.com>

### CODE REVIEW

**Comment by broady** [comment]
Why? If it's new, then ok will be false here:

```
	redirectURL, ok := oauthFlowSession.Values[oauthFlowRedirectKey].(string)
	// Validate this callback request came from the app.
	if !ok {
		return appErrorf(err, "invalid state parameter. try logging in again.")
	}
```

**Comment by huikang** [comment]
@broady if the season is new, that means this session is not callback session from previous login.

The ok tests if the redirect URL is a string type. Am I right?

**Comment by broady** [comment]
Yes, and it'll only be a string if it's not a new session.

It'll be nil if it's a new session, and fail the type check.

**Comment by huikang** [comment]
On Tue, Nov 7, 2017 at 4:06 PM, Chris Broadfoot <notifications@github.com>
wrote:

> Yes, and it'll only be a string if it's not a new session.
>
> It'll be nil if it's a new session, and fail the type check.
>
Thanks for your confirming. Shall I further make change to the PR or do you
think it is good?

**Comment by broady** [comment]
All good. Thanks!

**Comment by huikang** [comment]
@broady Does the PR fix the problem? I thought it should be merged to fix the problem of invalid session. No?

**Comment by broady** [comment]
I thought I explained why there's no problem. The "IsNew" check is redundant.

Can you explain how you came to an issue? Can you provide steps to reproduce?

**Pull request closed without merging**
