### PR TITLE
.travis.yml: use github.com/rakyll/gotest

### PR DESCRIPTION
**Pull request by broady**
This provides colorized test output.

### CODE REVIEW

**Comment by rakyll** [comment]
Whoa, this will be nice.

**Comment by broady** [comment]
Doesn't work. Guessing there's a missing environment variable for fatih/color.

**Comment by broady** [comment]
```
	NoColor = os.Getenv("TERM") == "dumb" ||
		(!isatty.IsTerminal(os.Stdout.Fd()) && !isatty.IsCygwinTerminal(os.Stdout.Fd()))

```

**Comment by rakyll** [comment]
Filed https://github.com/fatih/color/issues/80.

**Comment by rakyll** [comment]
You can test again, https://github.com/rakyll/gotest/commit/50cd4407f23f4faa76b3b5f699788b6e3a16e6c4 is merged.

**Pull request merged**
