### PR TITLE
fix(compute): fix compute API usage after some breaking changes

### PR DESCRIPTION
**Pull request by codyoss**

### CODE REVIEW

**Comment by codyoss** [comment]
This still required one more genrproto update to land before it can be merged.

**Comment by codyoss** [comment]
This should now pass.

**Comment by codyoss** [comment]
cc @noahdietz

**Comment by noahdietz** [comment]
Thank you for updating these.

**Review by tritone — APPROVED** [review]
Would love to get this merged in so the sample CI stops failing :)

**Comment by noahdietz** [comment]
Looks like there is something wrong with the Storage code

**Comment by noahdietz** [comment]
Potentially need to update to storage@v1.18.2?

**Comment by noahdietz** [comment]
Yeah updating version of storage to v1.18.2 should fix it.

**Pull request merged**
