### PR TITLE
securitycenter: initial commit

### PR DESCRIPTION
**Pull request by emkornfield**
This CL contains all snippets for CSCC documentation.

### CODE REVIEW

**Comment by tbpg** [comment]
I made some updates, so be sure to pull before making more changes.

There was this test failure:

```
--- FAIL: TestSetFindingState (0.13s)
    findings_test.go:263: setFindingState(organizations/1081635000895/sources/8675386348720965954/findings/updated) had error: SetFindingState: rpc error: code = PermissionDenied desc = Permission 'securitycenter.findings.setState' denied on resource 'organizations/1081635000895/sources/8675386348720965954/findings/updated' (or resource may not exist).
```

See https://source.cloud.google.com/results/invocations/cb30527a-d24c-4ff6-b64d-3dd4a67e453e/targets/gopath%2Fsrc%2Fgithub.com%2FGoogleCloudPlatform%2Fgolang-samples/tests.

I ran the tests many times locally and didn't have any issues. Only 1 out of 4 versions failed. So, it seems like some sort of flakiness issue. Maybe related to running tests in parallel?

**Comment by emkornfield** [comment]
@tbpg I think this failure might be to a small change in roles, that is potentially currently rolling out.  I pushed a change to further isolate the finding be updated.  Lets give the PR a few days and retest.

**Comment by emkornfield** [comment]
@tbpg I granted the service accounts permissions explicitly to the propagating permission.  Looking at the failures, they seem related to different products (mostly resource exhausted).

**Comment by tbpg** [comment]
Unrelated test failures ( :( ). Otherwise, looks good.

**Pull request merged**
