### PR TITLE
storage/objects: fix args check

### PR DESCRIPTION
**Pull request by sanleon**
I can't run with below command on Mac. 
So I fixed the source. 
command : GOOGLE_CLOUD_PROJECT=gcpproject bucket -o=bucket:notes write

### CODE REVIEW

**Comment by Winkies** [comment]
I agree, I can't run it too. 

Another way:

```
...
switch flag.Args()[0]:
....
```

**Comment by adams-sarah** [comment]
Confirmed, yea. Thank you.
It should be flag.Args(), you're right @Winkies 
Thanks all! I'll make this change.

**Comment by adams-sarah** [comment]
I apologize, my mistake. @sanleon your change was right on.
If you want to sign the CLA, I'll merge your change. 
Otherwise I can make the change myself.

**Comment by sanleon** [comment]
@adams-sarah Thank you for your review. Please merge PR.

**Comment by broady** [comment]
@sanleon could you please sign the CLA?

**Comment by sanleon** [comment]
@broady I signed the CLA yesterday. please confirm that.

**Comment by adams-sarah** [comment]
Hey @sanleon, on our end it does not look as though you've signed the CLA.
Can you double check that you used the same email address associated with your github account / your git commits? (see gobot comment above for instructions on how to check)

**Comment by sanleon** [comment]
@adams-sarah Sorry, I had a mistake that Authorized Signer of CLA. So I retry signed the CLA. Please confirm that.

**Comment by adams-sarah** [comment]
Hi @sanleon, sorry no it still looks as though you have not signed.
Please follow the instructions that google bot posted:

   Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

**Comment by sanleon** [comment]
@adams-sarah I confirm existing CLA data with below message.
> We don't have any individual agreements on file for you
I submitted new a CLA. but authorized signer can't be received an e-mail from Google.
So I want to ask about this problem. I can't find the contact. If have a problem about CLA. can need to ask to whom?

**Comment by adams-sarah** [comment]
@sanleon 
Please run:
```
git config --get user.email
```
What does it print?

What email are you using to sign the CLA?

**Comment by sanleon** [comment]
@adams-sarah Thank you for your reply.
I ran command the git config --get user.email.
So I'm Sorry, I confirm different to git email and now using email.
(I belong to two organization. another using Github Enterprise)
I made set git user.email for Qualiarts on golang-samples.(same email for CLA)
Please let know about next action.

**Comment by broady** [comment]
```
git commit --amend --reset-author
git push -f
```

**Comment by sanleon** [comment]
@broady thank you. I did it.

**Comment by broady** [comment]
Looks like your qualiarts e-mail hasn't signed the CLA (I manually checked).

**Comment by sanleon** [comment]
@broady thank you for your support.
I can see the 'Logged in as name@qualiarts.jp' on https://cla.developers.google.com/clas.
(name is my e-mail account name)
And I had an error 'It looks like you've already signed this CLA' when I was signed new an agreement.

**Comment by odeke-em** [comment]
How's it going @sanleon? Any new change with your CLA status so that we can get closer to merging your contribution in?

**Comment by sanleon** [comment]
@odeke-em I'm sorry for fixed about CLA. I sent new CLA yesterday. Please check it.

**Comment by odeke-em** [comment]
Awesome, thank you @sanleon, I'll defer this to @adams-sarah and @rakyll to perform the CLA check and perhaps merge then, since @broady is on vacation and I don't work at Google.

**Comment by rakyll** [comment]
@sanleon, it looks like "name@qualiarts.jp" hasn't signed the CLA on our system :( I will ask the CLA team what's going on.

**Comment by rakyll** [comment]
Thanks much! Sorry for the CLA check problem.

**Pull request merged**
