### PR TITLE
fix(dlp): Separated a tests files of samples for deid, inspect, jobs, metadata, redact and risk packages.

### PR DESCRIPTION
**Pull request by AarshD-crest**
## Description

- I have chosen not to divide the test files for the `template` and `trigger` packages. This decision was made because these test cases are structured to encompass create, update, list, and delete operations within a single test case, making optimal use of GCP resources. In this context, I believe this approach is the most efficient way to write these test cases. If we were to split them into different files, it might necessitate the creation of additional helper functions, potentially leading to increased utilization of GCP resources. Please do let me know if you have any further suggestions.

Fixes #3289 #3311 

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [X] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [X] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [X] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [X] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [X] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by telpirion** [comment]
I'm sorry, I can't accept this PR. Reasons:

+ 3K+ lines is too much for a single PR. Break this into multiple smaller PRs or abandon.
+ I don't agree with the reasoning for combining tests. This is against the [explicit guidance of the Style Guide](https://googlecloudplatform.github.io/samples-style-guide/#dedicated-testing-per-sample).

**Review by telpirion — CHANGES_REQUESTED** [review]
Please break this into smaller PRs.

**Comment by AarshD-crest** [comment]
> Please break this into smaller PRs.

Hey @telpirion, As per your suggestions I have broken this PR into smaller PRs each for 1 package of dip,  (#3327 for deid, #3328 for inspect, #3329 for jobs, #3330 for metadata, #3331 for risk, #3332 for template, #3333 for trigger related samples)

**Comment by AarshD-crest** [comment]
As per https://github.com/GoogleCloudPlatform/golang-samples/pull/3318#issuecomment-1746749206 closing this PR.

**Pull request closed without merging**
