### PR TITLE
chore(run/helloworld): update Go to 1.22

### PR DESCRIPTION
**Pull request by JulienBreux**
## Description

Update `helloworld` Cloud Run example to Go 1.22.

The main idea here is to update the documentation located here: https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-go-service
It's for this reason that this update is not global.

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [x] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [x] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Review by Deleplace — APPROVED** [review]
LGTM

**Comment by JulienBreux** [comment]
Why `Kokoro CI` failed?

**Comment by JulienBreux** [comment]
Hi @pattishin,

Could you help me 🤗 

Thanks!

**Comment by Deleplace** [comment]
Ha, [logs](https://btx.cloud.google.com/invocations/69b68f5a-305e-45e7-9135-cf3b43694a82/targets/cloud-devrel%2Fgo%2Fgolang-samples%2Fpresubmit%2Flatest-version;config=default/log) say:
```
=== Errors
go: go.mod requires go >= 1.22 (running go 1.21.11; GOTOOLCHAIN=local)
```

It is possible that some policy about supported Go version would sometimes prevent us from using the latest stable (Go 1.22) in our samples.

@muncus do you know if kokoro is running Go 1.21, preventing Go 1.22 ?

**Comment by muncus** [comment]
> @muncus do you know if kokoro is running Go 1.21, preventing Go 1.22 ?

Kokoro is running 1.21, and with 1.22, go.mod versions become **blocking** rather than advisory, so this has become an error.

Is go 1.22 required to run the sample? I doubt it since no code has changed. reverting the change to go.mod should fix the tests, and allow the sample to run with 1.21 on kokoro and 1.22 for customers

**Comment by telpirion** [comment]
We need to support the same versions of Go as the client libraries:
https://github.com/googleapis/google-cloud-go?tab=readme-ov-file#go-versions-supported

For that reason, I am going to delete this PR for now. Feel free to reopen once the window of supported versions is minimum 1.22. Thank you!

**Pull request closed without merging**
