### PR TITLE
feature(logging): Add a get sink sample

### PR DESCRIPTION
**Pull request by jhonatanlteodoro**
Refs: #1863

### CODE REVIEW

**Comment by enocom** [comment]
Adding some people from the logging team to take a look first. cc @arbrown @daniel-sanche

**Comment by jhonatanlteodoro** [comment]
> Adding some people from the logging team to take a look first. cc @arbrown @daniel-sanche

Is there someone else who could review this, @enocom ?

**Comment by enocom** [comment]
Let me ping the reviewers again and see what we can do.

**Comment by enocom** [comment]
Thanks for the contribution @jhonatanlteodoro, but after checking with the product team and reviewing our contribution guidelines, I'm going to close this. We will happily accept bug fixes, but don't accept new samples (or unused region tags).

Sorry for the trouble.

https://github.com/GoogleCloudPlatform/golang-samples#contributing-changes

**Pull request closed without merging**
