### PR TITLE
functions/helloworld: clarify that pubsub message data is already decoded

### PR DESCRIPTION
**Pull request by ace-n**
@tbpg not 100% positive on this - so please correct me if I'm wrong (and please **merge this PR for me** if I'm not! 🙂)

### CODE REVIEW

**Comment by grayside** [comment]
Agreed, the problem here is the developer is expecting to see something explicit, but golang is implicitly base64 decoding the data. Maybe it would be worth adding a comment to explain that?

**Comment by tbpg** [comment]
@ace-n, did you want to update this with @grayside's suggestion?

**Comment by ace-n** [comment]
@tbpg thanks for the ping - mind taking another look?

**Comment by broady** [comment]
FYI this PR title and commit message don't follow the style guide:

see 7 https://github.com/GoogleCloudPlatform/golang-samples/blob/master/CONTRIBUTING.md#contributing

eg

```
functions/helloworld: clarify that pubsub message data is already decoded
```

**Comment by ace-n** [comment]
Got it, updated. (Maybe y'all should ask DRIFT for a bot for that? 🙂)

**Pull request merged**
