### PR TITLE
chore(videointelligence): increase logo detection timeout to other lang standards

### LINKED ISSUE #1876: videointelligence/annotate: TestLogoDetectionGCS failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: 555da975282aa3ce627e7f003aaa5bf55fde9e25
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/68d2f663-d29a-43ea-a00e-6a2321792e74), [Sponge](http://sponge2/68d2f663-d29a-43ea-a00e-6a2321792e74)
status: failed

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Context: video API flaky across all languages 

Fixes #1876 #1877

### CODE REVIEW

**Review by sirtorry — APPROVED** [review]

**Comment by munkhuushmgl** [comment]
@tbpg Can u merge this for me?

**Review by tbpg — CHANGES_REQUESTED** [review]
This increases the delay between retry attempts. It doesn't increase the timeout of each individual attempt. Is that the intention?

**Comment by munkhuushmgl** [comment]
> This increases the delay between retry attempts. It doesn't increase the timeout of each individual attempt. Is that the intention?

I wanted to increase timeout on each attempt. How do I accomplish that?

**Comment by tbpg** [comment]
We don't currently set a timeout on the client side. If you wanted, you could overwrite `ctx` using [`context.WithTimeout`](https://golang.org/pkg/context/#WithTimeout) before this line:
https://github.com/GoogleCloudPlatform/golang-samples/blob/73d60a5de091dcdda5e4f753b594ef18eee67906/videointelligence/annotate/logo_detection_gcs.go#L42

Here is an example:
https://github.com/GoogleCloudPlatform/golang-samples/blob/73d60a5de091dcdda5e4f753b594ef18eee67906/storage/buckets/add_bucket_label.go#L39-L40

Of course, that will show up in the sample code itself, not just the test.

**Comment by munkhuushmgl** [comment]
@tbpg PTAL refactored accorinding to the feedback

**Review by tbpg — APPROVED** [review]

**Pull request merged**
