### PR TITLE
container_registry: update example to use effective severity to match the GCR UI

### PR DESCRIPTION
**Pull request by vtsao**

### CODE REVIEW

**Comment by vtsao** [comment]
@DanSanche

**Comment by vtsao** [comment]
Huh, this is a bug in our API, effective severity should be filled in by the API.
https://github.com/grafeas/grafeas/pull/400

will fix and then update this example once it goes live.

**Comment by tbpg** [comment]
Whoops! Thanks! Marking this as `do not merge` until then.

**Comment by DanSanche** [comment]
@vtsao Are we going to want this change implemented in all languages?

**Comment by tbpg** [comment]
Any updates here?

**Comment by vtsao** [comment]
Sorry for the delay, I'll get back to this next week.

**Comment by vtsao** [comment]
@DanSanche yeah we should do this for all client libs.

@tbpg the PR is ready to merge now, PTAL.

**Comment by tbpg** [comment]
Thanks!

**Pull request merged**
