### PR TITLE
trace: replace the obsolete client with OpenCensus

### PR DESCRIPTION
**Pull request by rakyll**

### CODE REVIEW

**Comment by rakyll** [comment]
Do not merge yet.

**Comment by broady** [comment]
Is this the right thing for the Trace docs?

Should we have a separate OC quickstart?

/cc @tbpg @SurferJeffAtGoogle

**Comment by rakyll** [comment]
This is for the Trace docs. We replaced cloud.google.com/go with OpenCensus for Go but the documentation still pointing to the old library.

We are going to move to OpenCensus for all other languages as well. I am working on it with @mtwo.

**Comment by broady** [comment]
merge whenever you're ready 👍

**Pull request merged**
