### PR TITLE
sample(compute): update create_snapshot.go error

### PR DESCRIPTION
**Pull request by m3libea**
Changed "create" by "get" in the create snapshot example.

### CODE REVIEW

**Review by tritone — APPROVED** [review]
Thanks for your contribution! We need to you sign the CLA in order to merge this -- see the link above.

**Comment by telpirion** [comment]
Hello @m3libea ! Thank you again for the contribution. If you would please sign the CLA, then we can merge this PR.

**Comment by m3libea** [comment]
Done!

**Comment by m3libea** [comment]
Is there anything else I need to do?

**Review by rsamborski — APPROVED** [review]

**Comment by telpirion** [comment]
@m3libea Thank you! It looks like we're all set to merge this.

**Review by telpirion — APPROVED** [review]

**Pull request merged**
