### PR TITLE
feat(dlp): Add code sample for using REP endpoint

### PR DESCRIPTION
**Pull request by jakubrauch**
## Description

Fixes: N/A

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [x] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [x] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Review by iennae — DISMISSED** [review]
This looks like it will need to go into a separate directory. 

Is this a new feature or a new version of the API? 

It's effectively the same sample as https://github.com/GoogleCloudPlatform/golang-samples/blob/main/dlp/snippets/inspect/inspect_string.go except for adding repLocation and the regional endpoint.

**Comment by jakubrauch** [comment]
> This looks like it will need to go into a separate directory.
Why?

> 
> Is this a new feature or a new version of the API?
No changes to the API, this just shows how to use the same API through dlp.<region>.rep.googleapis.com instead of dlp.googleapis.com. Same functionality, but provides in-transit regionalization.

> 
> It's effectively the same sample as https://github.com/GoogleCloudPlatform/golang-samples/blob/main/dlp/snippets/inspect/inspect_string.go except for adding repLocation and the regional endpoint.
Correct.

**Review by subfuzion — CHANGES_REQUESTED** [review]
Hi @jakubrauch, To @iennae's point, it definitely doesn't feel DRY to add so much code just to demonstrate adding an option, but, if this is something needed for the docs, then please go ahead and amend your commit message (and the update the PR title) to pass the conventional commits requirement (something like `feat(dlp):` would do it; see previously closed PRs for examples). Thanks!

**Comment by jakubrauch** [comment]
Thanks, updated, ptal

**Review by subfuzion — APPROVED** [review]

**Pull request merged**
