### PR TITLE
Chore(appengine_flexible): Update go versions to 1.21 for GAE Flex

### PR DESCRIPTION
**Pull request by kennethye1**
Update the Go versions for GAE flex to 1.21.

### CODE REVIEW

**Comment by jinglundong** [comment]
"Kokoro CI build failed" could you double check and see if it's caused by flakiness or something we need to fix.

**Comment by jinglundong** [comment]
I'm also seeing git conflicts "This branch has conflicts that must be resolved" in appengine_flexible/datastore/go.sum.

**Comment by kennethye1** [comment]
The Kokoro failed because testing/kokoro/latest-version.cfg is using go121. Seems unrelated.

**Comment by jinglundong** [comment]
Is Kokoro's Go supportability an issue that we can solve or mitigate? Having failing tests in the code base is a maintainability issue. Is it a reasonable compromise to upgrade the sample to 1.21 for now? 

```
=== Errors
go: go.mod requires go >= 1.22 (running go 1.21.1; GOTOOLCHAIN=local)
```

**Review by jinglundong — APPROVED** [review]
LGTM. It appears that the checks passed with the latest commit. Please update the title to reflect the version we chose. "Update go versions to 1.22 for GAE Flex".

**Pull request merged**
