### PR TITLE
copy modified Endpoints sample to new location

### PR DESCRIPTION
**Pull request by tangiel**
This change copies the sample from docs/managed_vms/endpoints/ to a new
endpoints/getting-started directory. It also generalizes the sample to
work on all GCP environments by adding a custom Dockerfile for use on
GCE and GKE, as well as creating a separate main function for non-App
Engine environments.

### CODE REVIEW

**Comment by broady** [comment]
A few questions:

* Why is this being copied, and not moved?
* The separate main functions are unnecessary. To support both MVM/Flex and GCE/GKE, do the following:
   * Default to port 8080.
   * Override the port number using the `PORT` environment variable.
   * For the GCE/GKE dockerfile, add a line with `ENV PORT 8081`.

```
port := "8080"
if p := os.Getenv("PORT") != "" {
  port = "8081"
}
log.Fatal(http.ListenAndServe(":"+port, nil))
```

Also, there are no docs for `Dockerfile.custom`?

It would be helpful if you added separate commits so the delta is clear.

**Comment by tangiel** [comment]
* It's being copied because the cloud docs aren't updated yet. Once they are, the old sample will be removed.
* But `appengine.Main` adds health checks in the case of Flex and so on. It's not just the port that's being customized.
* Lack of docs for Dockerfile.custom is intentional, they will be added to the cloud docs where we have quickstarts for using Docker. The goal here is to not have duplicate information in the README, which links to the quickstarts.

**Comment by broady** [comment]
The health checks will work just fine. A non-502/503/504 response is deemed healthy.

**Comment by tangiel** [comment]
Added a flag instead of using an environment variable. Is that acceptable?

**Comment by broady** [comment]
Nope, you need to use the `PORT` env variable for Flex. Also, move the main function back to where it was originally.

**Comment by tangiel** [comment]
What do you mean by "originally"? There was no main originally, only an init. If you mean to collapse it back into one file that makes sense.

**Comment by broady** [comment]
Original: https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/managed_vms/endpoints/app.go#L19-L36

**Comment by tangiel** [comment]
Oops, guess I changed it from main to init. Thought it was originally all in init. Pushed changes, testing them now.

**Comment by tangiel** [comment]
Verified that the docker image works and Flex deployment works.

**Pull request merged**
