### PR TITLE
internal/testutil: use os.Getwd to calculate Dir

### LINKED ISSUE #1275: testing: testutils does not accurately print out error
When running a test that lives in a product subdirectory, `testutils.go` will throw the following error if an invalid `.go` file exists at the top level of `$GOPATH/src/github.com/GoogleCloudPlatform/golang-samples/`:
 `testutil.go:62: could not find golang-samples directory`

### PR DESCRIPTION
**Pull request by tbpg**
I also made a couple small style fixes.

I ran `go build ./...` and it worked. So, I don't think we're using this anywhere (was necessary for `GOPATH` before modules).

It's possible we'll want something like this for E2E AppEngine testing in the future, but it's causing issues right now, so let's just remove it.

Fixes #1275.

### CODE REVIEW

**Comment by broady** [comment]
LGTM

**Comment by tbpg** [comment]
If we need it, we can look back in history. Dead code and all. :)

**Comment by tbpg** [comment]
Turns out, we did need `Dir` for AppEngine E2E tests. Not sure why `go build ./...` from the root passed... Maybe using a previous `testutil` module version?

I added it back using `os.Getwd`. Possibly not as correct as modules give no guarantee the directory path contains "golang-samples" but it works for now. :)

**Comment by broady** [comment]
go build ./... doesn't capture carved out modules

**Comment by tbpg** [comment]
`internal/testutil`, `internal/aeintegrate`, and `internal/e2e` are all in the same module (the root one).

**Pull request merged**
