### PR TITLE
chore: update infra to 1.19

### PR DESCRIPTION
**Pull request by quartzmo**
Based on #2203.

### CODE REVIEW

**Comment by quartzmo** [comment]
Do not merge until `gcr.io/golang-samples-tests/go119` has been built externally and is available.

**Comment by quartzmo** [comment]
```
Performing post processing steps...
................................................................................................................................................................................done.

Update done!
Removing intermediate container 90b1cca33626
 ---> 266ce288ed15
Successfully built 266ce288ed15
Successfully tagged gcr.io/golang-samples-tests/go119:latest
PUSH
DONE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ID                                    CREATE_TIME                DURATION  SOURCE                                                                                              IMAGES  STATUS
84e9680f-7408-48ed-b782-1c3a76493680  2022-08-09T18:14:30+00:00  18M3S     gs://golang-samples-tests_cloudbuild/source/1660068869.808078-90b12993c2ee40e98119ce8c957f9119.tgz  -       SUCCESS
```

**Review by codyoss — APPROVED** [review]

**Comment by quartzmo** [comment]
Hmmm... I thought I successfully built this (see comment above):

```
Error response from daemon: manifest for gcr.io/golang-samples-tests/go119:latest not found
Failed to pull docker image, attempt 0 out of 3.
Failed to pull docker image, attempt 1 out of 3.
Failed to pull docker image, attempt 2 out of 3.
Traceback (most recent call last):
  File "/tmpfs/src/gfile/trampoline_v1.py", line 132, in <module>
    main()
  File "/tmpfs/src/gfile/trampoline_v1.py", line 126, in main
    pull_docker_image(image)
  File "/tmpfs/src/gfile/trampoline_v1.py", line 66, in pull_docker_image
    raise RuntimeError("Failed to pull image {}.".format(image))
RuntimeError: Failed to pull image gcr.io/golang-samples-tests/go119.
+ cleanup
+ chmod +x /tmpfs/src/gfile/trampoline_cleanup.sh
+ /tmpfs/src/gfile/trampoline_cleanup.sh
+ echo cleanup
cleanup
```

**Comment by codyoss** [comment]
I will take this over in your absence.

**Pull request merged**
