### PR TITLE
datastore: change examples to use new key functions

### PR DESCRIPTION
**Pull request by jba**
We will remove the old ones soon.

DO NOT SUBMIT before we announce the changes (some time on October 31).

/cc @adams-sarah @zombiezen

### CODE REVIEW

**Comment by zombiezen** [comment]
:+1: code review

**Comment by broady** [comment]
LGTM

**Comment by broady** [comment]
BTW, @jba, you have write access to this repo, so you can push commits to a branch and create a PR from there. That way, the integration tests will run.

**Comment by jba** [comment]
Thanks, @broady, I will try to remember that.

**Comment by jba** [comment]
PTAL, did s/datastore.Done/iterator.Done/

**Comment by broady** [comment]
Could you send the iterator one as a separate PR? We can merge it right now.

`git cherry-pick 4b99e12`

**Comment by jba** [comment]
As far as compilation goes, we can merge them all right now -- the new key functions are in. I just don't want to risk someone looking at this repo, or having the snippets show up in cloud docs, before we announce changes. That will happen tomorrow hopefully.

**Comment by broady** [comment]
Merged it as 2127f4c

**Comment by jba** [comment]
urk. I hope the docs don't get regenerated today ...

**Comment by jba** [comment]
Oh, just the iterator, nvm.

**Comment by jba** [comment]
@broady This can now be merged.

**Pull request merged**
