### PR TITLE
fix(dlp): Separated a tests files of samples for `deid` package

### PR DESCRIPTION
**Pull request by AarshD-crest**
## Description

Fixes #3289

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [X] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [X] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [X] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [X] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [X] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by telpirion** [comment]
1297 lines of code is a lot to review! Please break this into smaller pieces, 500 LoC total change maximum.

**Review by telpirion — CHANGES_REQUESTED** [review]
issue: break PR into smaller pieces, please. Thank you!

**Comment by AarshD-crest** [comment]
> issue: break PR into smaller pieces, please. Thank you!

Hey @telpirion I have split this PR into 3 different PRs - `deid` PR - 1 #3340 , `deid` PR - 2 #3341 , `deid` PR - 3 #3342 
Could you please look at it whenever you get a chance.

**Comment by AarshD-crest** [comment]
> > issue: break PR into smaller pieces, please. Thank you!
> 
> Hey @telpirion I have split this PR into 3 different PRs - `deid` PR - 1 #3340 , `deid` PR - 2 #3341 , `deid` PR - 3 #3342 Could you please look at it whenever you get a chance.

Hence Closing this PR.

**Pull request closed without merging**
