### PR TITLE
docs/.../sendgrid: pin to v2 sendgrid API

### PR DESCRIPTION
**Pull request by broady**

### CODE REVIEW

**Comment by jonparrott** [comment]
LGTM, but how would you feel about just using their API directly?

**Comment by broady** [comment]
@jonparrott I wrote that, too, but it seemed worse.

https://github.com/GoogleCloudPlatform/golang-samples/pull/59/files

**Comment by jonparrott** [comment]
Ah I see, well, carry on.

**Comment by broady** [comment]
Maybe for later.

**Pull request merged**
