### PR TITLE
jobs: v4 patch

### PR DESCRIPTION
**Pull request by anguillanneuf**
- update auto-complete sample to search PUBLIC jobs
- update create-job-with-custom-atttributes sample with explicit employment type

### CODE REVIEW

**Comment by anguillanneuf** [comment]
@tbpg I still don't understand why sometimes the tests fail.

**Comment by beccasaurus** [comment]
Additional request:

While porting the samples, I was confused by the `ranking_expression` used in the Custom Ranking Search sample because it uses `someFieldLong` in its expression. Took me awhile to figure out the sample works because a _different_ sample creates a custom attribute with this name.

Let's update it to use a built-in field on job.

/cc @chenlei1216 for recommendations on a realish expression please!!

Comment on LOC from first PR: https://github.com/GoogleCloudPlatform/golang-samples/pull/778/files#r266266931

**Comment by chenlei1216** [comment]
> Additional request:
> 
> While porting the samples, I was confused by the `ranking_expression` used in the Custom Ranking Search sample because it uses `someFieldLong` in its expression. Took me awhile to figure out the sample works because a _different_ sample creates a custom attribute with this name.
> 
> Let's update it to use a built-in field on job.
> 
> /cc @chenlei1216 for recommendations on a realish expression please!!
> 
> Comment on LOC from first PR: https://github.com/GoogleCloudPlatform/golang-samples/pull/778/files#r266266931



> Additional request:
> 
> While porting the samples, I was confused by the `ranking_expression` used in the Custom Ranking Search sample because it uses `someFieldLong` in its expression. Took me awhile to figure out the sample works because a _different_ sample creates a custom attribute with this name.
> 
> Let's update it to use a built-in field on job.
> 
> /cc @chenlei1216 for recommendations on a realish expression please!!
> 
> Comment on LOC from first PR: https://github.com/GoogleCloudPlatform/golang-samples/pull/778/files#r266266931



> Additional request:
> 
> While porting the samples, I was confused by the `ranking_expression` used in the Custom Ranking Search sample because it uses `someFieldLong` in its expression. Took me awhile to figure out the sample works because a _different_ sample creates a custom attribute with this name.
> 
> Let's update it to use a built-in field on job.
> 
> /cc @chenlei1216 for recommendations on a realish expression please!!
> 
> Comment on LOC from first PR: https://github.com/GoogleCloudPlatform/golang-samples/pull/778/files#r266266931

Built-in fields are not allowed in ranking_expression, but we only accept the customer-defined keys in custom attributes like 'someFieldLong'.

**Comment by anguillanneuf** [comment]
@tbpg @broady @jadekler Not sure why the tests would fail for a random combination of go19, 110, 111, and 112.

**Comment by chenlei1216** [comment]
@anguillanneuf 

Sorry Tianzi, as xinyunh@ replied in the email, we've done some field renaming on the API request recently as we gone through some other API reviews with Luke. Most significantly we renamed "name" as "parent" in "CompleteQueryRequest", and we rename "company_names" as "companies" in "Job" entity. As a result we may need to do some small changes in the Go code samples.

We've just finalized the schema right now, and xinyunh@ is working on publishing the new client libraries accordingly. We'll deploy the latest version to our production server by April 9th, and hopefully everything should work by then.

**Pull request merged**
