### PR TITLE
pubsub: fix the race in tests

### LINKED ISSUE #104: pubsub: flaky test, bad error message
```
main_test.go:59: got [0xc8204e2440 0xc8204e2460]; want the list with topic = "golang-samples-topic-example""
```

### PR DESCRIPTION
**Pull request by rakyll**
Fixes #104.

### CODE REVIEW

**Comment by rakyll** [comment]
We should probably apply something similar for all subscriptions and topics.

**Comment by broady** [comment]
Still failed with

```
got [0xc420389140 0xc420389180 0xc4203891a0]; want a list with topic = "golang-samples-topic-example-topic""   
```

Can you update that test to produce a better output?

**Comment by rakyll** [comment]
This is coming from the topics tests, let me isolate them as well. And will fix the output.

**Comment by rakyll** [comment]
Closing in the favor of https://github.com/GoogleCloudPlatform/golang-samples/pull/111.

**Pull request closed without merging**
