### PR TITLE
docs/.../sendgrid: update to sendgrid v3 API

### PR DESCRIPTION
**Pull request by broady**

### CODE REVIEW

**Comment by broady** [comment]
Note: still doesn't work for GAE standard.

**Comment by odeke-em** [comment]
@broady looks like we have some merge conflicts + need a rebase.

**Comment by tbpg** [comment]
@broady, is this still needed?

**Comment by broady** [comment]
Might be worth another look. We were blocked on Sendgrid adding some features to their client (well, actually, I tried to add the feature but got blocked on their overreaching CLA). I think it was just the ability to set HTTP client (i.e., urlfetch).

**Comment by grayside** [comment]
It looks like we've stopped maintaining detailed instructions on this integration, instead linking to relevant developer/api resources for each external messaging service: https://cloud.google.com/appengine/docs/flexible/go/sending-messages

Perhaps this PR should be closed in favor of another purging the sample?

**Comment by tbpg** [comment]
Sounds good to me!

**Comment by tbpg** [comment]
Went to delete the sample, but looks like it was already deleted in #1013. :)

**Pull request closed without merging**
