### PR TITLE
the url pattern is not working

### PR DESCRIPTION
**Pull request by tristan-lin**
The url in the handlers, `/tasks/process`, does not work for taskqueue_push.go, where we use `/` and `/worker`.

### CODE REVIEW

**Comment by tristan-lin** [comment]
~ friendly ping ~
Any chance to get merged into the main branch?

**Comment by broady** [comment]
Shouldn't we replace it with `/worker`?

**Comment by tristan-lin** [comment]
I don't think `/worker` could work for `/`. We can change it to `/worker/.*`, but we also need to modify the handler path in the `taskqueue_push.go` accordingly.

**Comment by tristan-lin** [comment]
gentle ping~

**Comment by broady** [comment]
I think it should be something like:


```
// [START securing_urls]
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
- url: /worker/.*
  script: _go_app
  login: admin
// [END securing_urls]
```

**Comment by tristan-lin** [comment]
Done!

**Comment by tristan-lin** [comment]
@broady 
Hi! Can we merge this CL now?

**Comment by broady** [comment]
thank you!

**Pull request merged**
