### PR TITLE
all: add go.mod file

### PR DESCRIPTION
**Pull request by broady**
DO NOT SUBMIT

Created with:
$ go mod init
$ go get -u github.com/mailgun/mailgun-go@master

(mailgun has made some backwards incompatible changes, and they're
likely tagging this repo with v2 soon)

Everything builds with go build ./... from outside a GOPATH.

We probably want separate go.mod files for deployed apps (App Engine samples,
Bookshelf app).

### CODE REVIEW

**Comment by broady** [comment]
Especially curious if `github.com/gofrs/uuid/v3` builds on <go1.11

**Comment by tbpg** [comment]
Thanks! We should probably update the testing logic for Go 1.11 to enable modules.

**Comment by broady** [comment]
Yep, fail on uuid/v3.

```
package github.com/gofrs/uuid/v3: cannot find package "github.com/gofrs/uuid/v3" in any of: /usr/local/go/src/github.com/gofrs/uuid/v3 (from $GOROOT) /tmpfs/src/gopath/src/github.com/gofrs/uuid/v3 (from $GOPATH)
```

**Comment by broady** [comment]
Looks like artifact caching is broken:

```
+ gimmeproj -project golang-samples-tests done golang-samples-tests-8
Returned golang-samples-tests-8 to the pool.


[ID: 5166649] Build finished after 57 secs, exit value: 1


Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
rsync: send_files failed to open "/tmpfs/src/gopath/pkg/mod/cache/download/bitbucket.org/ckvist/twilio/@v/v0.0.0-20170512072134-13c593a1721b.info": Permission denied (13)
rsync: send_files failed to open "/tmpfs/src/gopath/pkg/mod/cache/download/bitbucket.org/ckvist/twilio/@v/v0.0.0-20170512072134-13c593a1721b.mod": Permission denied (13)
```

http://sponge/07a9264f-40c6-4465-a83b-31f995e00118

**Comment by tbpg** [comment]
Will follow up with another PR to make sure 1.11 tests use modules.

**Comment by broady** [comment]
1.11 uses modules! I set the env variable for every version

**Comment by tbpg** [comment]
Doh! Sorry I missed that. Looks great!

**Comment by broady** [comment]
Do we want individual go.mod alongside any of the directories that have Dockerfile or app.yaml? I think so.

**Comment by tbpg** [comment]
Yes, I think so. Those are "independent" applications.

**Comment by tbpg** [comment]
I made a bunch of updates to get this working. Only Go 1.10 failed the last round of testing due to an unrelated failure:

```
--- FAIL: TestSample (2.16s)
	leaderboard_test.go:81: run("createdatabase", "projects/golang-samples-tests/instances/golang-samples-tests/databases/test--golang-samples-tests-2"): rpc error: code = AlreadyExists desc = Database already exists: projects/golang-samples-tests/instances/golang-samples-tests/databases/test--golang-samples-tests-2
```

So, I think this is ready to go.

@jadekler, will you review? Another pair of eyes would be nice since I made a bunch of updates after @broady's start.

**Pull request merged**
