### PR TITLE
spanner: add context param to ReadWriteTransaction

### LINKED ISSUE #261: spanner: sample needs update
Breaking changes broke the samples:
https://code-review.googlesource.com/#/c/12852/
https://code-review.googlesource.com/#/c/13230/

/cc @vkedia @jba

### PR DESCRIPTION
**Pull request by broady**
https://code-review.googlesource.com/#/c/12852/

Fixes #261.

### CODE REVIEW

**Comment by broady** [comment]
Could also remove the ctx param to getBudget. WDYT, @jba ? /cc @rakyll

**Comment by jba** [comment]
@broady yes, remove ctx param to getBudget.

**Comment by rakyll** [comment]
lgtm

**Comment by broady** [comment]
Also removed `txn` parameter.

Headed out for the day. @rakyll can you submit when this looks good/green?

**Comment by rakyll** [comment]
@broady, done!

**Pull request merged**
