### PR TITLE
chore: add ability to source general secrets from secret manager

### PR DESCRIPTION
**Pull request by codyoss**
This is a common pattern other projects are already using. Extending
this pattern to samples for our cross functional teams.

Related: 453992095

### CODE REVIEW

**Comment by codyoss** [comment]
cc @JesseLovelace

**Comment by tritone** [comment]
Looks like kokoro is unhappy though

**Comment by codyoss** [comment]
@tritone Yeah, the linked CL needs to be merged first, I will refresh kokoro after this.

**Comment by JesseLovelace** [comment]
CL has been pushed, I reran the tests and they're still failing, but I think it's unrelated?

**Comment by codyoss** [comment]
Yes, the failure is unrelated and there is an open bug for that issue. I will force merge this for now.

**Pull request merged**
