### PR TITLE
docs: remove dual-homed region tags

### PR DESCRIPTION
**Pull request by Strykrol**
Removes unused region tags now that the new tags have proliferated in docs.

### CODE REVIEW

**Comment by Strykrol** [comment]
Looking into region tag violations..

**Comment by Strykrol** [comment]
cl/376017137 submitted for fix, should pass snippet bot on the next pass.

**Review by tbpg — COMMENTED** [review]
Generally looks good, but will wait for the bot to be happy.

**Comment by Strykrol** [comment]
The CL to fix violations was manually published last week, and I just updated the branch to rerun... Fingers crossed that the violations disappear.

**Comment by Strykrol** [comment]
Please merge when ready, I don't have authorization to do so :) Thank you!

**Review by tbpg — APPROVED** [review]

**Pull request merged**
